import { Category, Lesson } from "@/types";

export const CATEGORIES: Category[] = [
  "วิทย์",
  "คณิต",
  "ภาษาไทย",
  "ภาษาอังกฤษ",
  "สังคม",
  "เทคโนโลยี",
  "ทักษะชีวิต",
  "อื่นๆ",
];

export const CATEGORY_COLORS: Record<Category, { bg: string; text: string; border: string; badge: string; icon: string }> = {
  "วิทย์": {
    bg: "bg-emerald-50",
    text: "text-emerald-700",
    border: "border-emerald-200",
    badge: "bg-emerald-100 text-emerald-800",
    icon: "🔬",
  },
  "คณิต": {
    bg: "bg-blue-50",
    text: "text-blue-700",
    border: "border-blue-200",
    badge: "bg-blue-100 text-blue-800",
    icon: "📐",
  },
  "ภาษาไทย": {
    bg: "bg-amber-50",
    text: "text-amber-700",
    border: "border-amber-200",
    badge: "bg-amber-100 text-amber-800",
    icon: "📚",
  },
  "ภาษาอังกฤษ": {
    bg: "bg-purple-50",
    text: "text-purple-700",
    border: "border-purple-200",
    badge: "bg-purple-100 text-purple-800",
    icon: "🌍",
  },
  "สังคม": {
    bg: "bg-rose-50",
    text: "text-rose-700",
    border: "border-rose-200",
    badge: "bg-rose-100 text-rose-800",
    icon: "🏛️",
  },
  "เทคโนโลยี": {
    bg: "bg-sky-50",
    text: "text-sky-700",
    border: "border-sky-200",
    badge: "bg-sky-100 text-sky-800",
    icon: "💻",
  },
  "ทักษะชีวิต": {
    bg: "bg-orange-50",
    text: "text-orange-700",
    border: "border-orange-200",
    badge: "bg-orange-100 text-orange-800",
    icon: "🌱",
  },
  "อื่นๆ": {
    bg: "bg-indigo-50",
    text: "text-indigo-700",
    border: "border-indigo-200",
    badge: "bg-indigo-100 text-indigo-800",
    icon: "✨",
  },
};

export const DEFAULT_PASSING_SCORE = 70;
export const MAX_IMAGE_SIZE_BYTES = 5 * 1024 * 1024; // 5MB
export const LESSON_CARD_LIMIT = 20;

// High-quality sample lessons with Pixar/Cute 3D themes for immediate learning & testing
export const INITIAL_SEED_LESSONS: Lesson[] = [
  {
    id: "lesson-photosynthesis-3min",
    title: "การสังเคราะห์ด้วยแสงใน 3 นาที! 🌱☀️",
    description: "เข้าใจกระบวนการเปลี่ยนแสงอาทิตย์เป็นพลังงานของพืชแบบง่ายๆ พร้อมภาพ Chibi น่ารัก",
    objective: "เข้าใจสมการการสังเคราะห์ด้วยแสง ปัจจัยที่จำเป็น และผลผลิตที่ได้จากพืช",
    thumbnailUrl: "https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?w=800&auto=format&fit=crop&q=80",
    authorId: "teacher-1",
    authorName: "ครูพี่เมฆ ☁️",
    estimatedMinutes: 3,
    category: "วิทย์",
    tags: ["วิทยาศาสตร์", "พืช", "ชีววิทยา", "ธรรมชาติ"],
    passingScore: 70,
    isPublished: true,
    deletedAt: null,
    createdAt: "2026-09-28T10:00:00.000Z",
    updatedAt: "2026-09-28T10:00:00.000Z",
    cards: [
      {
        id: "c1",
        type: "text-image",
        title: "พืชกินอาหารอย่างไร? 🍃",
        body: "พืชเป็น 'ผู้ผลิต' ที่เก่งกาจมาก! พวกมันไม่ได้กินข้าวเหมือนเรา แต่ใช้ 'คลอโรฟิลล์' ในใบไม้เพื่อดูดจับแสงอาทิตย์ แล้วผสมเข้ากับน้ำจากรากและก๊าซคาร์บอนไดออกไซด์จากอากาศ เพื่อปรุงเป็นอาหารเอง",
        imageUrl: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800&auto=format&fit=crop&q=80",
      },
      {
        id: "c2",
        type: "slide",
        imageUrl: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&auto=format&fit=crop&q=80",
        caption: "สูตรง่ายๆ: น้ำ + ก๊าซคาร์บอนไดออกไซด์ + แสงแดด = น้ำตาลกลูโคส (อาหารพืช) + ก๊าซออกซิเจนบริสุทธิ์ 🌬️✨",
      },
      {
        id: "c3",
        type: "quiz",
        question: "ก๊าซชนิดใดที่พืช 'ปล่อยออกมา' สู่บรรยากาศหลังการสังเคราะห์ด้วยแสง?",
        options: [
          "ก๊าซคาร์บอนไดออกไซด์",
          "ก๊าซออกซิเจน",
          "ก๊าซไนโตรเจน",
          "ก๊าซฮีเลียม",
        ],
        correctIndex: 1,
        explanation: "ถูกต้อง! พืชจะปล่อยก๊าซออกซิเจน (O₂) ออกมาให้มนุษย์และสัตว์ได้หายใจอย่างสดชื่น 🌿",
      },
      {
        id: "c4",
        type: "quiz",
        question: "สารสีเขียวในใบไม้ที่ทำหน้าที่ดูดซับพลังงานแสงคืออะไร?",
        options: [
          "คลอโรฟิลล์ (Chlorophyll)",
          "เมลานิน (Melanin)",
          "ฮีโมโกลบิน (Hemoglobin)",
          "แคโรทีนอยด์ (Carotenoid)",
        ],
        correctIndex: 0,
        explanation: "เป๊ะมาก! คลอโรฟิลล์คือรงควัตถุสีเขียวที่ทำหน้าที่เสมือนแผงโซลาร์เซลล์ของพืช 💚",
      },
    ],
  },
  {
    id: "lesson-ai-prompting-4min",
    title: "เคล็ดลับคุยกับ AI ให้ได้งานเป๊ะใน 4 นาที 🤖✨",
    description: "เรียนรู้เทคนิค Prompt Engineering เบื้องต้น: Role + Task + Context + Format",
    objective: "สามารถเขียนคำสั่ง (Prompt) ที่ชัดเจนและได้รับผลลัพธ์ที่ตรงจุดจาก Generative AI",
    thumbnailUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    authorId: "teacher-1",
    authorName: "ครูบอตตี้ 🤖",
    estimatedMinutes: 4,
    category: "เทคโนโลยี",
    tags: ["AI", "เทคโนโลยี", "Prompt", "การทำงาน"],
    passingScore: 70,
    isPublished: true,
    deletedAt: null,
    createdAt: "2026-09-28T11:00:00.000Z",
    updatedAt: "2026-09-28T11:00:00.000Z",
    cards: [
      {
        id: "c1",
        type: "text-image",
        title: "ทำไม AI ถึงตอบไม่ตรงใจ? 🧠",
        body: "ถ้าเราสั่งว่า 'เขียนบทความให้หน่อย' AI จะเดาใจเราไม่ถูก! กุญแจสำคัญคือโครงสร้าง RTCF: Role (สวมบทบาท) + Task (งานที่ต้องทำ) + Context (บริบท/กลุ่มเป้าหมาย) + Format (รูปแบบผลลัพธ์ที่ต้องการ)",
        imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop&q=80",
      },
      {
        id: "c2",
        type: "slide",
        imageUrl: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&auto=format&fit=crop&q=80",
        caption: "ตัวอย่าง: 'คุณเป็นนักโภชนาการ (Role) ช่วยแนะนำเมนู 3 วัน (Task) สำหรับคนออกกำลังกาย (Context) ในรูปแบบตาราง (Format)'",
      },
      {
        id: "c3",
        type: "quiz",
        question: "ตัวอักษร 'R' ในเทคนิค RTCF ย่อมาจากอะไร?",
        options: [
          "Result (ผลลัพธ์)",
          "Role (บทบาทหน้าที่)",
          "Requirement (ข้อกำหนด)",
          "Rule (กฎเกณฑ์)",
        ],
        correctIndex: 1,
        explanation: "ถูกต้อง! Role คือการกำหนดให้ AI สวมบทบาทผู้เชี่ยวชาญในด้านนั้นๆ 🎭",
      },
      {
        id: "c4",
        type: "quiz",
        question: "ข้อใดคือการระบุ 'Format' ที่ดีที่สุดสำหรับ Prompt?",
        options: [
          "เขียนมาให้ยาวๆ หน่อยนะ",
          "สรุปเป็น Bullet points 5 ข้อ พร้อมตัวหนาที่คีย์เวิร์ดสำคัญ",
          "ตอบให้ดีที่สุด",
          "เอาตามใจ AI เลย",
        ],
        correctIndex: 1,
        explanation: "ยอดเยี่ยม! การระบุโครงสร้างผลลัพธ์ชัดเจน (เช่น Bullet 5 ข้อ) จะได้งานที่นำไปใช้ต่อได้ทันที 📋",
      },
    ],
  },
  {
    id: "lesson-compound-interest-3min",
    title: "พลังดอกเบี้ยทบต้น: เงินงอกเงยแบบมหัศจรรย์ 💰📈",
    description: "ทำความเข้าใจว่าทำไม Albert Einstein ถึงยกย่องดอกเบี้ยทบต้นเป็นสิ่งมหัศจรรย์อันดับ 8 ของโลก",
    objective: "เข้าใจหลักการทำงานของดอกเบี้ยทบต้นและพลังของ 'ระยะเวลา'",
    thumbnailUrl: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&auto=format&fit=crop&q=80",
    authorId: "teacher-2",
    authorName: "ครูส้มโอ 🍊",
    estimatedMinutes: 3,
    category: "ทักษะชีวิต",
    tags: ["การเงิน", "การลงทุน", "ดอกเบี้ย", "ออมเงิน"],
    passingScore: 70,
    isPublished: true,
    deletedAt: null,
    createdAt: "2026-09-28T12:00:00.000Z",
    updatedAt: "2026-09-28T12:00:00.000Z",
    cards: [
      {
        id: "c1",
        type: "text-image",
        title: "ดอกเบี้ยธรรมดา vs ดอกเบี้ยทบต้น 🚀",
        body: "ดอกเบี้ยธรรมดาคิดจากเงินต้นเดิมเสมอ แต่ดอกเบี้ยทบต้น (Compound Interest) จะนำผลตอบแทนที่ได้ 'กลับไปรวมเป็นเงินต้นใหม่' ทำให้เงินต้นก้อนใหญ่ขึ้นเรื่อยๆ เหมือนลูกหิมะกลิ้งลงเขา!",
        imageUrl: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&auto=format&fit=crop&q=80",
      },
      {
        id: "c2",
        type: "quiz",
        question: "ปัจจัยที่สำคัญที่สุดที่ทำให้ดอกเบี้ยทบต้นแสดงพลังทวีคูณสูงสุดคืออะไร?",
        options: [
          "การเปลี่ยนธนาคารบ่อยๆ",
          "ระยะเวลา (Time) ในการลงทุนอย่างต่อเนื่อง",
          "การถอนเงินออกมาใช้ทุกเดือน",
          "การลงทุนเฉพาะตอนตลาดหุ้นตก",
        ],
        correctIndex: 1,
        explanation: "ถูกต้องครับ! ยิ่งลงทุนเร็วและปล่อยให้เงินทำงานนานเท่าไร ผลตอบแทนจะเติบโตแบบก้าวกระโดด (Exponential Growth) ⏳✨",
      },
    ],
  },
  {
    id: "lesson-thai-proverbs-3min",
    title: "สำนวนไทยที่คนมักใช้ผิด! 📖🐘",
    description: "เช็คความเข้าใจสำนวนไทยยอดฮิตใน 3 นาที พร้อมที่มาที่สนุกสนาน",
    objective: "ใช้สำนวนสุภาษิตไทยได้อย่างถูกต้องตามบริบทและความหมายดั้งเดิม",
    thumbnailUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80",
    authorId: "teacher-1",
    authorName: "ครูพี่เมฆ ☁️",
    estimatedMinutes: 3,
    category: "ภาษาไทย",
    tags: ["ภาษาไทย", "สำนวน", "ไวยากรณ์"],
    passingScore: 100,
    isPublished: true,
    deletedAt: null,
    createdAt: "2026-09-28T13:00:00.000Z",
    updatedAt: "2026-09-28T13:00:00.000Z",
    cards: [
      {
        id: "c1",
        type: "text-image",
        title: "สำนวน 'กระต่ายตื่นตูม' 🐇💥",
        body: "หมายถึง ผู้ที่ตื่นตกใจง่ายโดยยังไม่ได้ตรวจสอบข้อเท็จจริง มีที่มาจากนิทานชาดกที่กระต่ายนอนใต้ต้นตาล ลูกตาลตกกระทบใบไม้เสียงดัง กระต่ายตกใจคิดว่าแผ่นดินถล่มจึงวิ่งเตลิดพาเพื่อนสัตว์แตกตื่น",
        imageUrl: "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=800&auto=format&fit=crop&q=80",
      },
      {
        id: "c2",
        type: "quiz",
        question: "สำนวนใดหมายถึง 'การทำงานที่ลงทุนมากหรือเสี่ยงมาก แต่ได้ผลตอบแทนเพียงเล็กน้อย'?",
        options: [
          "ขี่ช้างจับตั๊กแตน",
          "จับปลาสองมือ",
          "ตำน้ำพริกละลายแม่น้ำ",
          "ชี้โพรงให้กระรอก",
        ],
        correctIndex: 0,
        explanation: "ถูกต้อง! 'ขี่ช้างจับตั๊กแตน' คือลงทุนใหญ่โตเพื่อผลลัพธ์เล็กนิดเดียว ส่วนตำน้ำพริกละลายแม่น้ำคือเสียทรัพย์โดยไม่ได้ประโยชน์อะไรเลย 🐘✨",
      },
    ],
  },
];
